### ISSUE TITLE
unexpected assigned value in the output of ct$eval

### ISSUE THREAD

**Issue by stla** [jeroenooms/V8#13]
Hello,

```
> ct$eval("var x=[];")
> ct$eval("x[0]=2;")
[1] "2"
```

Is there a way not to get the assigned value in the output ?

**Comment by jeroenooms** [comment]
What you are seeing is not the assigned value; it is console output from running this line. You would see the same thing when running these two lines in another javascript console, for example node or chrome. If you wish to hide output in R you can wrap your calls in `invisible()`.

In this case, the reason that the console is printing the value of your assignment is that javascript assignments return the assigned value in order to support chained assignments: `foo = x[0] = 2;`

**Comment by stla** [comment]
Ok. In fact I'm trying to use V8 as an engine in knitr but I don't know how to handle this "problem". 
https://groups.google.com/d/topic/knitr/CkTo7j_DgDU/discussion
